Repository Jordan141/articleblog, pull requests merged in 2020-12, with the labels that each got.

#20 Security
  .gitignore
  app.js
  middleware/index.js
  package-lock.json
  package.json
  routes/index.js
  seeds.js
  views/login.ejs
  views/register.ejs
Labels: WIP, enhancement, functionality

#27 Hot reloading
  Dockerfile
  app/.eslintrc.json
  app/app.js
  app/cypress/fixtures/example.json
  app/cypress/integration/sample.spec.js
  app/cypress/plugins/index.js
  app/cypress/support/commands.js
  app/cypress/support/index.js
  app/middleware/index.js
  app/models/article.js
  app/models/comment.js
  app/models/user.js
  app/nodemon.json
  app/playground.js
  app/public/scripts/search.js
  app/public/stylesheets/landing.css
  app/public/stylesheets/main.css
  app/routes/articles.js
  app/routes/comments.js
  app/routes/index.js
  app/views/articles/edit.ejs
  app/views/articles/index.ejs
  app/views/articles/new.ejs
  app/views/articles/show.ejs
  app/views/comments/edit.ejs
  app/views/comments/new.ejs
  app/views/landing.ejs
  app/views/login.ejs
  app/views/partials/footer.ejs
  app/views/partials/header.ejs
  app/views/register.ejs
  app/views/users/edit.ejs
  app/views/users/show.ejs
  docker-compose.yml
  package.json
Labels: enhancement, functionality

#28 Add Account Types
  README.md
  app/app.js
  app/middleware/index.js
  app/models/article.js
  app/models/user.js
  app/public/scripts/markdown.js
  app/public/stylesheets/main.css
  app/routes/articles.js
  app/views/articles/approve.ejs
  app/views/articles/index.ejs
  app/views/articles/show.ejs
  app/views/landing.ejs
  app/views/login.ejs
  app/views/partials/footer.ejs
  app/views/partials/header.ejs
  app/views/register.ejs
Labels: functionality

#59 58 (subtask) desktop article view
  designs/README.md
  designs/assets/account.svg
  designs/assets/image-placeholder.png
  designs/assets/logo.svg
  designs/assets/noise.png
  designs/assets/pencil.svg
  designs/desktop.html
  designs/desktop/article.html
  designs/desktop/footer.html
  designs/desktop/header.html
  designs/desktop/right-panel.html
  designs/desktop/top-stories.html
  designs/shared-classes.css
  designs/shared/button.html
  designs/shared/comment.html
  designs/shared/edit-field.html
  designs/shared/edit-icon.html
  designs/style.css
Labels: Aesthetic

#60 58 (subtask) articles listing desktop
  designs/article-view.html
  designs/articles-listing-homepage.html
  designs/articles-listing.html
  designs/desktop/article.html
  designs/desktop/articles-listing-homepage.html
  designs/desktop/articles-listing.html
  designs/desktop/footer.html
  designs/desktop/partials/footer.html
  designs/desktop/partials/header.html
  designs/desktop/partials/right-panel.html
  designs/desktop/partials/top-stories.html
  designs/desktop/views/article/author-panel.html
  designs/desktop/views/article/comments-section.html
  designs/desktop/views/article/page-content.html
  designs/desktop/views/article/page-title.html
  designs/desktop/views/article/recommended-article.html
  designs/desktop/views/articles-listing/listed-article.html
  designs/desktop/views/articles-listing/page-content.html
  designs/desktop/views/articles-listing/page-title.html
  designs/desktop/views/articles-listing/top-article.html
  designs/general-page-styles.css
  designs/style.css
  package-lock.json
Labels: Aesthetic

#65 58 (subtask) categories listing
  designs/article-edit.html
  designs/assets/error.svg
  designs/author-profile.html
  designs/authors.html
  designs/categories-listing.html
  designs/desktop/article-edit.html
  designs/desktop/author-profile.html
  designs/desktop/authors.html
  designs/desktop/categories-listing.html
  designs/desktop/edit-profile.html
  designs/desktop/error-page.html
  designs/desktop/login.html
  designs/desktop/register.html
  designs/desktop/views/article-edit/category-selector.html
  designs/desktop/views/article-edit/image-upload.html
  designs/desktop/views/article-edit/page-content.html
  designs/desktop/views/article-edit/page-title.html
  designs/desktop/views/author-profile/page-content.html
  designs/desktop/views/author-profile/page-title.html
  designs/desktop/views/author-profile/social-network.html
  designs/desktop/views/authors/author-entry.html
  designs/desktop/views/authors/page-content.html
  designs/desktop/views/authors/page-title.html
  designs/desktop/views/categories-listing/listed-category.html
  designs/desktop/views/categories-listing/page-content.html
  designs/desktop/views/categories-listing/page-title.html
  designs/desktop/views/edit-profile/page-content.html
  designs/desktop/views/edit-profile/page-title.html
  designs/desktop/views/error-page/page-content.html
  designs/desktop/views/error-page/page-title.html
  designs/desktop/views/login/page-content.html
  designs/desktop/views/login/page-title.html
  designs/desktop/views/register/page-content.html
  designs/desktop/views/register/page-title.html
  designs/edit-profile.html
  designs/error-page.html
  designs/login.html
  designs/register.html
  designs/shared-classes.css
  designs/shared/confirmation-modal.html
  designs/style.css
Labels: Aesthetic

#67 Image Uploading
  .gitignore
  Dockerfile
  app/.eslintrc.json
  app/app.js
  app/public/scripts/markdown.js
  app/public/stylesheets/main.css
  app/routes/articles.js
  app/routes/index.js
  app/views/articles/new.ejs
  app/views/register.ejs
  app/views/users/edit.ejs
  app/views/users/show.ejs
  docker-compose.yml
  package-lock.json
  package.json
Labels: MVP, PRIORITY, functionality

#73 58 mobile layout
  designs/article-view.html
  designs/articles-listing-homepage.html
  designs/articles-listing.html
  designs/categories-listing.html
  designs/desktop/article.html
  designs/desktop/articles-listing-homepage.html
  designs/desktop/articles-listing.html
  designs/desktop/authors.html
  designs/desktop/categories-listing.html
  designs/desktop/partials/footer.html
  designs/desktop/partials/header.html
  designs/desktop/partials/right-panel.html
  designs/desktop/partials/top-stories.html
  designs/desktop/views/article/comments-section.html
  designs/desktop/views/article/page-content.html
  designs/desktop/views/article/page-title.html
  designs/desktop/views/article/recommended-article.html
  designs/desktop/views/articles-listing/listed-article.html
  designs/desktop/views/articles-listing/top-article.html
  designs/desktop/views/author-profile/page-content.html
  designs/desktop/views/author-profile/page-title.html
  designs/desktop/views/authors/author-entry.html
  designs/desktop/views/authors/page-content.html
  designs/desktop/views/categories-listing/listed-category.html
  designs/desktop/views/edit-profile/page-content.html
  designs/desktop/views/login/page-content.html
  designs/desktop/views/register/page-content.html
  designs/general-page-styles.css
  designs/shared-classes.css
  designs/shared/edit-field.html
  designs/style.css
Labels: Aesthetic

#82 root ejs component
  app/app.js
  app/old_views/articles/approve.ejs
  app/old_views/articles/edit.ejs
  app/old_views/articles/index.ejs
  app/old_views/articles/list.ejs
  app/old_views/articles/new.ejs
  app/old_views/articles/show.ejs
  app/old_views/comments/edit.ejs
  app/old_views/comments/new.ejs
  app/old_views/landing.ejs
  app/old_views/login.ejs
  app/old_views/pages/root.ejs
  app/old_views/partials/footer.ejs
  app/old_views/partials/header.ejs
  app/old_views/register.ejs
  app/old_views/users/edit.ejs
  app/old_views/users/show.ejs
  app/public/assets/account.svg
  app/public/assets/error.svg
  app/public/assets/image-placeholder.png
  app/public/assets/logo.svg
  app/public/assets/noise.png
  app/public/assets/pencil.svg
  app/public/scripts/glide.js
  app/public/stylesheets/footer.css
  app/public/stylesheets/general-page-styles.css
  app/public/stylesheets/header.css
  app/public/stylesheets/landing.css
  app/public/stylesheets/main.css
  app/public/stylesheets/shared-classes.css
  app/public/stylesheets/style.css
  app/routes/index.js
  app/views/index.ejs
  app/views/pages/article-listing.ejs
  app/views/partials/footer.ejs
  app/views/partials/header.ejs
Labels: MVP, WIP, frontend

#76 WYSIWYG & Article Images
  app/public/scripts/utils.js
  app/routes/articles.js
  app/routes/index.js
  app/views/pages/article.ejs
  app/views/pages/components/article-edit/image-upload.ejs
  app/views/pages/components/article-edit/page-content.ejs
  app/views/pages/components/articles-listing/listed-article.ejs
  app/views/pages/components/articles-listing/top-article.ejs
  app/views/partials/footer.ejs
  visualeditor.html
Labels: Aesthetic, WIP, frontend, functionality

#116 Extract image functionality to utils
  app/public/scripts/utils.js
  app/routes/articles.js
  app/routes/index.js
  app/utils.js
  app/views/pages/components/article/page-content.ejs
  config/redis.conf
Labels: PRIORITY, backend, bug, frontend

#118 Categories Route
  app/app.js
  app/models/article.js
  app/routes/articles.js
  app/routes/index.js
  app/staticdata/categories.json
  app/utils.js
  app/views/pages/categories.ejs
  app/views/pages/components/article-edit/category-selector.ejs
  app/views/pages/components/categories-listing/listed-category.ejs
  app/views/pages/components/categories-listing/page-content.ejs
Labels: BLOCKED, PRIORITY, backend, frontend, functionality

#130 #62 unique counter
  app/app.js
  app/models/routeCounter.js
  app/public/scripts/browser-signature.js
  app/public/scripts/utils.js
  app/routes/analytics.js
  app/views/partials/footer.ejs
Labels: PRIORITY, backend, frontend, functionality

#128 Add content-type to get image
  app/utils.js
Labels: PRIORITY, backend, bug

#129 Change to onDOMLoaded
  app/public/scripts/utils.js
  app/views/partials/footer.ejs
Labels: PRIORITY, Performance, frontend

#119 minmax inputs
  app/models/article.js
  app/models/comment.js
  app/models/user.js
  app/routes/articles.js
  app/routes/index.js
  app/staticdata/minmax.json
  app/views/pages/article-edit.ejs
  app/views/pages/components/article-edit/page-content.ejs
  app/views/pages/components/article/comment-section.ejs
  app/views/pages/components/edit-profile/page-content.ejs
  app/views/pages/edit-profile.ejs
  app/views/pages/login.ejs
  app/views/pages/register.ejs
Labels: PRIORITY, backend

#138 137 autodeploy script
  .github/workflows/basic.yml
  devops/README.md
  devops/clear-mongodb.sh
  devops/hooks.json
  devops/redeploy.sh
  devops/start.sh
Labels: devops

#143 Quick Bug Fixes
  app/models/article.js
  app/public/scripts/utils.js
  app/routes/articles.js
  app/routes/index.js
  app/utils.js
  app/views/pages/authors.ejs
  app/views/pages/categories.ejs
  app/views/pages/components/article-edit/page-content.ejs
  app/views/partials/header.ejs
Labels: PRIORITY, bug

#146 139 styling fixes on mobile
  app/public/stylesheets/general-page-styles.css
  app/public/stylesheets/header.css
  app/public/stylesheets/style.css
Labels: Aesthetic, bug, frontend, styling

#120 Proper logging of errors
  app/app.js
  app/logger.js
  app/routes/analytics.js
  app/routes/articles.js
  app/routes/comments.js
  app/routes/index.js
  app/utils.js
  package-lock.json
  package.json
Labels: PRIORITY, Security, backend

#148 145 fixed cursor for category tiles
  app/public/stylesheets/category-listing.css
Labels: Accesability, bug, frontend, styling

#158 Remove orphaned images
  app/utils.js
Labels: Performance, backend, question

#157 Social Media
  app/models/user.js
  app/public/assets/social-network-codepen.png
  app/public/assets/social-network-github.png
  app/public/assets/social-network-linkedin.png
  app/public/stylesheets/author-profile.css
  app/routes/index.js
  app/views/pages/components/author-profile/page-content.ejs
  app/views/pages/components/author-profile/social-network.ejs
  app/views/pages/components/edit-profile/page-content.ejs
Labels: backend, bug, frontend, frontent logic

#165 164 cursor pointer for author panel
  app/public/stylesheets/author-panel.css
Labels: Accesability, Aesthetic, bug, frontend, styling

#156 Common Categories
  app/app.js
  app/public/scripts/utils.js
  app/public/stylesheets/author-panel.css
  app/public/stylesheets/header.css
  app/public/stylesheets/right-panel.css
  app/public/stylesheets/shared-classes.css
  app/public/stylesheets/style.css
  app/routes/index.js
  app/utils.js
  app/views/pages/components/article/author-panel.ejs
  app/views/pages/components/articles-listing/page-content.ejs
  app/views/pages/partials/right-panel.ejs
  app/views/partials/header.ejs
Labels: PRIORITY, backend, bug, frontend, frontent logic, styling

#173 170 fixed header issues for articles listing and inputs
  app/public/stylesheets/listed-article.css
  app/public/stylesheets/shared-classes.css
  app/views/partials/header.ejs
Labels: bug, styling

#174 169 fixed notification styling
  app/public/stylesheets/shared-classes.css
  app/public/stylesheets/style.css
  app/views/partials/header.ejs
Labels: bug, styling

#176 175 captcha visibility on mobile
  app/old_views/login.ejs
  app/public/stylesheets/shared-classes.css
  app/views/pages/login.ejs
  app/views/pages/register.ejs
Labels: bug, styling

#181 Bug fixes
  app/app.js
  app/routes/articles.js
  app/routes/index.js
Labels: PRIORITY, backend, bug

#188 186 article ordering fix
  app/views/pages/components/articles-listing/page-content.ejs
Labels: bug, frontend, frontent logic

#187 182 fixed word breaks
  app/public/stylesheets/article.css
Labels: bug, frontend, styling

#190 110 comment panel visible again
  app/public/stylesheets/comment-section.css
  app/public/stylesheets/style.css
Labels: frontend, styling

#191 153 CSS bg -> img migration
  app/public/stylesheets/category-listing.css
  app/public/stylesheets/listed-article.css
  app/public/stylesheets/shared-classes.css
  app/public/stylesheets/top-stories.css
  app/views/pages/article.ejs
  app/views/pages/components/article/author-panel.ejs
  app/views/pages/components/articles-listing/listed-article.ejs
  app/views/pages/components/articles-listing/top-article.ejs
  app/views/pages/components/author-profile/page-content.ejs
  app/views/pages/components/categories-listing/listed-category.ejs
  app/views/pages/partials/top-stories.ejs
  app/views/partials/header.ejs
Labels: SEO, frontend, styling

#194 192 elipsizing texts of listed articles
  app/public/scripts/utils.js
  app/public/stylesheets/listed-article.css
  app/views/pages/components/articles-listing/listed-article.ejs
Labels: frontend, frontent logic

#196 96 remove unsafe inline csp
  app/app.js
  app/public/stylesheets/edit-profile.css
  app/public/stylesheets/header.css
  app/public/stylesheets/listed-article.css
  app/views/pages/components/edit-profile/page-content.ejs
  app/views/partials/header.ejs
Labels: Security, frontend, frontent logic, styling

#185 Change routes to title
  app/middleware/index.js
  app/models/article.js
  app/models/routeCounter.js
  app/models/user.js
  app/routes/analytics.js
  app/routes/articles.js
  app/routes/comments.js
  app/routes/index.js
  app/utils.js
  app/views/pages/article.ejs
  app/views/pages/components/article-edit/page-content.ejs
  app/views/pages/components/article/author-panel.ejs
  app/views/pages/components/article/comment-section.ejs
  app/views/pages/components/article/page-content.ejs
  app/views/pages/components/articles-listing/listed-article.ejs
  app/views/pages/components/articles-listing/top-article.ejs
  app/views/pages/components/author-profile/page-content.ejs
  app/views/pages/components/authors/author-entry.ejs
  app/views/pages/components/edit-profile/page-content.ejs
  app/views/pages/partials/top-stories.ejs
  app/views/partials/header.ejs
  package-lock.json
  package.json
  seeds.js
  visualeditor.html
Labels: Security, backend, frontend, frontent logic, refactor
