Repository Jordan141/articleblog, pull requests merged in 2021-02, with the labels that each got.

#321 317 converted img to picture and webp support
  __tests__/e2e/healthCheck.spec.js
  app/imageUtils.js
  app/routes/articles.js
  app/routes/index.js
  app/seed.js
  app/staticdata/ci_dummydata.json
  app/staticdata/dummydata.json
  app/utils.js
  app/views/pages/components/author-profile/page-content.ejs
  app/views/partials/footer.ejs
  app/views/partials/header.ejs
  app/views/ssrUtils/responsiveImage.ejs
  defaultEnv
Labels: BLOCKED, PRIORITY, WIP, backend, frontend, frontent logic

#325 User profile Access
  app/routes/index.js
  app/views/pages/components/edit-profile/page-content.ejs
  app/views/partials/header.ejs
Labels: PRIORITY, backend, bug, frontend, frontent logic

#330 graceful shutdown
  app/app.js
Labels: backend, refactor
