Repository Jordan141/articleblog, pull requests merged in 2021-01, with the labels that each got.

#206 Url bugfixes
  app/models/article.js
  app/routes/articles.js
  app/routes/comments.js
  app/routes/index.js
  app/utils.js
  app/views/pages/components/articles-listing/listed-article.ejs
  app/views/pages/components/articles-listing/top-article.ejs
  package-lock.json
  package.json
Labels: PRIORITY, bug

#201 Article Searching
  app/app.js
  app/models/article.js
  app/public/assets/search.svg
  app/public/scripts/utils.js
  app/public/stylesheets/header.css
  app/routes/index.js
  app/utils.js
  app/views/pages/article-listing.ejs
  app/views/pages/components/articles-listing/page-title.ejs
  app/views/partials/header.ejs
  package-lock.json
  package.json
Labels: WIP, backend, frontent logic

#202 Email Verification
  README.md
  app/mailer.js
  app/middleware/index.js
  app/models/user.js
  app/models/verify.js
  app/routes/index.js
  package-lock.json
  package.json
Labels: WIP, backend

#213 Newsletter
  app/mailer.js
  app/models/newsletter.js
  app/old_views/articles/edit.ejs
  app/public/scripts/utils.js
  app/public/stylesheets/footer.css
  app/routes/articles.js
  app/routes/index.js
  app/utils.js
  app/views/pages/unsubscribe.ejs
  app/views/partials/footer.ejs
Labels: Feature Request, backend, frontend, frontent logic

#214 207 cursor pointer fix for logo and top stories
  app/public/stylesheets/header.css
  app/public/stylesheets/top-stories.css
Labels: Accesability, bug, frontend, styling

#219 Smart scaling fix
  app/routes/articles.js
  app/routes/index.js
  app/utils.js
Labels: PRIORITY, backend, bug

#224 Recommended Articles
  app/routes/articles.js
  app/views/pages/article.ejs
  app/views/pages/components/article/recommended-article.ejs
Labels: Aesthetic, backend, frontent logic

#223 Bugfix - Image Naming
  app/models/article.js
  app/routes/articles.js
  app/routes/index.js
  app/utils.js
Labels: PRIORITY, backend, bug

#222 Populate Author
  app/models/article.js
  app/routes/articles.js
  app/routes/index.js
Labels: backend, bug

#225 Seed Database
  app/app.js
  app/content/images/article/dummy.jpeg
  app/content/images/profile/dummy.jpeg
  app/seed.js
  app/staticdata/dummydata.json
  app/utils.js
Labels: backend, devops

#227 Author drafts
  app/middleware/index.js
  app/public/stylesheets/author-profile.css
  app/routes/articles.js
  app/views/pages/components/author-profile/page-content.ejs
  app/views/pages/draft-listing.ejs
Labels: backend, frontend, frontent logic

#226 Privacy policy
  app/app.js
  app/routes/index.js
  app/views/pages/gdprpolicy.ejs
  app/views/pages/privacypolicy.ejs
  app/views/partials/footer.ejs
Labels: Accesability, backend, frontend

#228 Docker Things
  package.json
Labels: devops

#239 Add more seed articles
  app/staticdata/dummydata.json
Labels: backend, devops

#220 Load More Pagination
  app/public/scripts/utils.js
  app/routes/index.js
  app/utils.js
  app/views/pages/components/articles-listing/page-content.ejs
Labels: Feature Request, PRIORITY, WIP, backend, frontend, frontent logic

#238 Multiple Categories
  app/models/article.js
  app/routes/articles.js
  app/seed.js
  app/staticdata/dummydata.json
  app/utils.js
  app/views/pages/components/article-edit/category-selector.ejs
Labels: WIP, backend, frontend, frontent logic

#241 Devops
  .gitignore
  app/app.js
  app/views/partials/header.ejs
  devops/clear-mongodb.sh
  devops/redeploy.sh
  devops/start.sh
  docker-compose.yml
Labels: devops

#245 devops fix
  .dockerignore
  .gitignore
  devops/README.md
  devops/clear-mongodb.sh
  devops/redeploy.sh
  devops/start.sh
Labels: bug, devops

#248 DDoS Sensitivity
  app/app.js
  app/routes/articles.js
  app/routes/index.js
Labels: Security, backend, bug

#215 199 responsive images
  app/public/stylesheets/listed-article.css
  app/routes/index.js
  app/utils.js
  app/views/pages/article.ejs
  app/views/pages/components/article/author-panel.ejs
  app/views/pages/components/article/recommended-article.ejs
  app/views/pages/components/articles-listing/listed-article.ejs
  app/views/pages/components/articles-listing/top-article.ejs
  app/views/pages/components/authors/author-entry.ejs
  app/views/pages/components/categories-listing/listed-category.ejs
  app/views/pages/partials/top-stories.ejs
  app/views/partials/header.ejs
  app/views/ssrUtils/responsiveImage.ejs
Labels: Performance, frontend

#257 gitignore dummy image exceptions
  .gitignore
Labels: bug, devops

#259 246 fix permissions issue with mongo container
  devops/clear-mongodb.sh
  docker-compose.yml
Labels: PRIORITY, bug, devops

#264 Improvements to Docker setup
  Dockerfile
  README.md
  app/app.js
  devops/clear-mongodb.sh
  devops/redeploy.sh
  devops/up.sh
  docker-compose.yml
  package.json
Labels: PRIORITY, devops, refactor

#268 Mobile view ruined
  app/public/stylesheets/article-page-content.css
  app/public/stylesheets/style.css
Labels: PRIORITY, REGRESSION, bug

#269 255 center listed category
  app/public/stylesheets/category-listing.css
Labels: Aesthetic, bug, frontend

#271 270 fixed logo dimensions on mobile
  app/public/stylesheets/header.css
Labels: Aesthetic, bug

#253 Joi Sanitising
  app/public/scripts/utils.js
  app/routes/analytics.js
  app/routes/articles.js
  app/routes/comments.js
  app/routes/index.js
  app/validation/index.js
  app/validation/schemas/analytics/fingerprintSchema.js
  app/validation/schemas/articles/createArticleSchema.js
  app/validation/schemas/articles/index.js
  app/validation/schemas/articles/updateArticleSchema.js
  app/validation/schemas/comments/createCommentSchema.js
  app/validation/schemas/comments/deleteCommentSchema.js
  app/validation/schemas/comments/updateCommentSchema.js
  app/validation/schemas/edituser.js
  app/validation/schemas/index/editAuthorSchema.js
  app/validation/schemas/index/index.js
  app/validation/schemas/index/indexRouteSchema.js
  app/validation/schemas/index/loginSchema.js
  app/validation/schemas/index/registerSchema.js
  app/validation/schemas/index/subscribeSchema.js
  app/validation/schemas/index/unsubscribeSchema.js
  app/validation/schemas/index/verifyEmailSchema.js
  app/views/pages/components/article-edit/page-content.ejs
  app/views/pages/components/edit-profile/page-content.ejs
  package-lock.json
  package.json
Labels: Security, backend, refactor

#278 Repeat Password Enforcement
  app/validation/schemas/index/editAuthorSchema.js
  app/validation/schemas/index/registerSchema.js
  app/views/pages/components/edit-profile/page-content.ejs
  app/views/pages/register.ejs
Labels: PRIORITY, backend, bug

#280 Bugfixes
  app/validation/schemas/index/editAuthorSchema.js
  app/validation/schemas/index/registerSchema.js
Labels: PRIORITY, REGRESSION, backend, bug

#277 Meaningful Joi Errors
  app/validation/index.js
Labels: PRIORITY, backend

#281 276 glidejs throws errors
  app/views/ssrUtils/responsiveImage.ejs
Labels: PRIORITY, bug, frontend, frontent logic

#251 Switch to .exec() variants of mongoose operations
  app/routes/articles.js
  app/routes/comments.js
  app/routes/index.js
Labels: backend, refactor

#284 254 tablet view
  app/public/stylesheets/article-listing/page-content.css
  app/public/stylesheets/article-page-content.css
  app/public/stylesheets/article.css
  app/public/stylesheets/author-entry.css
  app/public/stylesheets/author-page-content.css
  app/public/stylesheets/author-panel.css
  app/public/stylesheets/author-profile.css
  app/public/stylesheets/category-listing.css
  app/public/stylesheets/general-page-styles.css
  app/public/stylesheets/listed-article.css
  app/public/stylesheets/shared-classes.css
  app/public/stylesheets/style.css
  app/public/stylesheets/top-article.css
  app/public/stylesheets/top-article/top-article.css
  app/public/stylesheets/top-stories.css
  app/views/pages/article-listing.ejs
  app/views/pages/components/edit-profile/page-content.ejs
  app/views/pages/partials/top-stories.ejs
  app/views/partials/header.ejs
Labels: Accesability, Aesthetic, PRIORITY, bug, frontend

#292 197 confirmation modal
  app/public/scripts/utils.js
  app/public/stylesheets/confirmation-modal.css
  app/views/pages/components/article-edit/page-content.ejs
  app/views/pages/components/edit-profile/page-content.ejs
  app/views/pages/partials/confirmation-modal.ejs
  app/views/partials/confirmation-modal.ejs
  app/views/partials/header.ejs
Labels: frontend, frontent logic

#293 Basic categories
  app/public/assets/categories/android.jpg
  app/public/assets/categories/casestudy.jpg
  app/public/assets/categories/cpp.jpg
  app/public/assets/categories/csharp.jpg
  app/public/assets/categories/devops.jpg
  app/public/assets/categories/java.jpg
  app/public/assets/categories/javascript.jpg
  app/public/assets/categories/linux.jpg
  app/public/assets/categories/mac.jpg
  app/public/assets/categories/programming.jpg
  app/public/assets/categories/typescript.jpg
  app/public/assets/categories/v8.jpg
  app/public/assets/categories/wasm.jpg
  app/public/assets/categories/webgl.jpg
  app/public/assets/categories/windows.jpg
  app/public/stylesheets/category-listing.css
  app/staticdata/categories.json
  app/views/pages/components/categories-listing/listed-category.ejs
Labels: Aesthetic, frontend

#288 Slugify and Canonicals
  app/app.js
  app/modelUtils.js
  app/models/article.js
  app/models/link.js
  app/models/user.js
  app/routes/articles.js
  app/routes/index.js
  app/seed.js
  app/staticdata/minmax.json
  app/staticdata/slugify_options.json
  app/utils.js
  app/validation/schemas/articles/createArticleSchema.js
  app/validation/schemas/articles/updateArticleSchema.js
  app/views/partials/header.ejs
  package-lock.json
  package.json
Labels: SEO, Security, backend, frontent logic, refactor

#306 305 article editor cache too aggressive
  app/public/scripts/utils.js
  app/views/pages/components/article-edit/page-content.ejs
Labels: bug, frontend, frontent logic

#308 307 category selector restyling
  app/public/stylesheets/category-selector.css
  app/views/pages/components/article-edit/category-selector.ejs
Labels: Aesthetic, frontend

#311 295 less aggressive image placeholder
  app/public/assets/image-placeholder.png
  app/public/stylesheets/article.css
  app/public/stylesheets/author-entry.css
  app/public/stylesheets/author-panel.css
  app/public/stylesheets/author-profile.css
  app/public/stylesheets/category-listing.css
  app/public/stylesheets/edit-profile.css
  app/public/stylesheets/header.css
  app/public/stylesheets/listed-article.css
  app/public/stylesheets/recommended-article.css
  app/public/stylesheets/right-panel.css
  app/public/stylesheets/shared-classes.css
  app/public/stylesheets/style.css
  app/public/stylesheets/top-article.css
  app/public/stylesheets/top-article/top-article.css
  app/public/stylesheets/top-stories.css
Labels: Aesthetic, frontend

#312 262 health check
  .github/workflows/auto-deploy.yml
  .github/workflows/health-check.yml
  __tests__/e2e/healthCheck.spec.js
  app/routes/index.js
  defaultEnv
  package-lock.json
  package.json
Labels: devops

#252 Author categories
  app/public/stylesheets/author-entry.css
  app/public/stylesheets/author-panel.css
  app/public/stylesheets/author-profile.css
  app/public/stylesheets/category-listing.css
  app/routes/index.js
  app/utils.js
  app/views/pages/components/article/author-panel.ejs
  app/views/pages/components/author-profile/page-content.ejs
  app/views/pages/components/authors/author-entry.ejs
Labels: WIP, backend, frontend, frontent logic

#299 Delete account
  app/public/scripts/utils.js
  app/public/stylesheets/confirmation-modal.css
  app/routes/index.js
  app/views/pages/components/edit-profile/page-content.ejs
  app/views/partials/confirmation-modal.ejs
  app/views/partials/footer.ejs
  app/views/partials/header.ejs
Labels: backend, frontend, frontent logic

#315 273 change password bug
  app/app.js
  app/routes/index.js
  app/utils.js
  app/validation/schemas/index/editAuthorSchema.js
Labels: backend, bug
